### ISSUE TITLE
Not working anymore for me

### ISSUE THREAD

**Issue by rayman89** [Dook1/Closed-tabs-windows-Restorer#2]
Something happened and now no tabs are displayed on the closed tab list.  I tested on my everyday profile and my wife's one with the same results.

I also tested disabling all the addons but yours with the same result.

![imagen](https://user-images.githubusercontent.com/5449042/38754412-59cb4ab8-3f27-11e8-9c51-2ecfc447d9ce.png)

**Comment by Dook1** [comment]
What is your version of Firefox? I tested it on Firefox 60b12- everything works. 
Check in the clean new profile. 
What is the value of browser.sessionstore.max_tabs_undo?

**Comment by rayman89** [comment]
Im using firefox dev 60b12 my wife uses firefox release 59

I have on  browser.sessionstore.max_tabs_undo 50 and she has 30.

Like I said I disabled all the addons but yours. Restarted the browser and the problem persist. So I dont think it's a compatibility issue.

**Comment by Dook1** [comment]
Check in the new profile.

**Comment by rayman89** [comment]
New profile opened a bunch of tabs and closed them. Like you can see on most visited.

![image](https://user-images.githubusercontent.com/5449042/38755694-54c07642-3f2c-11e8-8bcf-a3b3485642a0.png)

**Comment by Dook1** [comment]
I dont know. No one else complained.

**Comment by rayman89** [comment]
Any ideas on what can I try?

**Comment by rayman89** [comment]
I tested other undo close tab addons and no tabs appear on the list either. So it's probably something on my side. Control + shit +T works though.  Any Ideas of what can I try to fix it?

**Comment by Dook1** [comment]
No ideas.

**Comment by rayman89** [comment]
I fixed it. I changed browser.sessionstore.max_tabs_undo to default 10 and deleted recent browsing history  that made it work again but IDK why it happened in first place. 

I tested changing it back to 50 opening and closing 50+ tabs  and restarting the browser and it cotinued working properly so maybe something of the profile got corrupted on a firefox update idk.

**Comment by Dook1** [comment]
I am glad. It's strange that the creation of a new profile did not help.
