### ISSUE TITLE
Must have updated? Broken now.

### ISSUE THREAD

**Issue by TheWayOfYahweh** [Dook1/Closed-tabs-windows-Restorer#3]
The drop down no longer looks like the preview pics on the addon page.
Control/Select no longer works
Shift/Select no longer works
Remove button doesn't work
Control/Select/Clear Selection button doesn't work
Options page no longer is the same as shown on the addon page as well.

What happened? Please fix, as this was the absolute best closed tabs addon available, and now, it's broken.

![closed tabs issue](https://user-images.githubusercontent.com/31078076/52282990-42a3b880-2927-11e9-9cd4-30eb51b44a49.PNG)

Can we get the prior version back which worked perfectly?

**Comment by Dook1** [comment]
Remove/restore in the absence of selection - fixed in 2.0.1. New selection method work fine - selection only with the left or right mouse buttons (and optionally Ctrl). About a new design and a new method selection -  there will be no return to the old one.

**Comment by TheWayOfYahweh** [comment]
Ok, thank you, just got 2.0.1, and it's working again.

Question though: will you be readding the shiftkey/select group feature back again? This was very useful in some cases. Or is the control key/select all that will be available now?

**Comment by Dook1** [comment]
Selection now work by moving mouse while pressing LMB or RMB. Single item selection - single click RMB or Ctrl+LMB

**Comment by TheWayOfYahweh** [comment]
Ok, disregard, figured it out :)
