### ISSUE TITLE
2.0.3 font size is so big.

### ISSUE THREAD

**Issue by DandyClubs** [Dook1/Closed-tabs-windows-Restorer#4]
pls add option change font size.

**Comment by Dook1** [comment]
Attach fullscreen screenshot

**Comment by DandyClubs** [comment]
1.4.1
https://drive.google.com/file/d/1MqikiQtBTbeVPHtL2sEgXJH8fNkQutQY/view?usp=sharing

2.0.3
https://drive.google.com/file/d/1Wy_I-f9WByWS015k_K6QaVITR9iu3gGv/view?usp=sharing

**Comment by Dook1** [comment]
difference is not fundamental

**Comment by DandyClubs** [comment]
i think font difference.

**Comment by Dook1** [comment]
Firefox->Options->Language and Appearance->Font size

**Comment by DandyClubs** [comment]
i try change font and size 

font size all apply.

i use NanumFont

NanumFont  apply only korean language

english and japanese and digital is not apply.

**Comment by Dook1** [comment]
Added to 2.1.0

**Comment by DandyClubs** [comment]
thanks!!
good job!
