### ISSUE TITLE
Close tabs clearing issue

### ISSUE THREAD

**Issue by TheWayOfYahweh** [Dook1/Closed-tabs-windows-Restorer#5]
Hi,

We began experiencing this issue today (see attachment) when removing closed tab items from the drop down list. The items do go away, but only after closing and reopening the list does the clearing become visible, unlike previously where the items would just clear and the list would adjust.

Thanks!

![unclose issue](https://user-images.githubusercontent.com/31078076/52657250-dcd2a600-2ebd-11e9-8952-afe93ae40cc0.PNG)
![unclose issue 2](https://user-images.githubusercontent.com/31078076/52657364-202d1480-2ebe-11e9-8aad-ed56d493203d.PNG)

**Comment by Dook1** [comment]
fixed in 2.2.2

**Comment by TheWayOfYahweh** [comment]
Closer. It seems the "Close addon window after restore/remove" in options is causing issues.

1. When unchecked in options, the list in the addon window works as it should, removing individual/group selections, they clear from the list, but, as it should, being unchecked, the add on window remains open.

2. When it is checked to close the addon window, that's where the issues return, the list of closed tabs in the addon window don't remove/clear, the single/group selections remain in the addon window and the addon window remains open even though it's checkmarked to close.

So, with the "Close addon window after restore/remove" checked, the list in the addon window should continue to function just as in #1 above, except addon window should close.

**Comment by Dook1** [comment]
Fixed in 2.2.3 - now really fix

**Comment by TheWayOfYahweh** [comment]
Perfect, that's it :)

Thank you!
