### ISSUE TITLE
Does not working

### ISSUE THREAD

**Issue by Stepan-H** [Dook1/Closed-tabs-windows-Restorer#6]
Does not show any list of closed pages.
![does_not_working](https://user-images.githubusercontent.com/31160576/71366147-78827780-25a1-11ea-8729-6abdf95b47c0.png)

**Comment by Dook1** [comment]
Everything works. Create a new profile and try in it.

**Comment by Stepan-H** [comment]
It started work... I did not change anything including not create new profile...
