### ISSUE TITLE
Reopens the wrong entry

### ISSUE THREAD

**Issue by harl** [Dook1/Closed-tabs-windows-Restorer#7]
For some reason, when I click on one entry in the list, this sometimes reopens another one instead, often some kind of resized window, maybe from a popup or something similar that had been loaded some time ago but wasn't supposed to ever actually show up. (I know this may sound weird but it's the best way I can describe this issue.)
It does this every few times I want to restore a tab from the list, and it's not related to a certain page or domain.  All my tabs are in a single window so there shouldn't be any other windows, ever.

Also, I've tried to clear the list (in case there's something wrong with it and clearing it may fix it) and that seemed to work at first, but after closing another tab or restarting FF, the whole list is back to where it was.

This add-on is the only one I've found that's able to save more than 25 closed tabs, so I'd appreciate if you could look into this and don't hesitate to ask in case of further questions.

**Comment by Dook1** [comment]
It's Mozilla's bug - https://bugzilla.mozilla.org/show_bug.cgi?id=1538119

**Comment by konto-andrzeja** [comment]
Is it possible to have some workaround implemented? When I'm clicking on an entry, it has a proper url displayed, so maybe opening a new tab with that url would work?

**Comment by Dook1** [comment]
Recovery goes through the firefox API. If I restore by URL, I’ll lose: the history of the tab, its position relative to the rest of the tabs, belonging to a specific window, etc.

**Comment by konto-andrzeja** [comment]
Ok, makes sense, thanks for the explanation. I wonder if it won't be better to restore it without history and next to the current tab, but with proper url. At least until they fix the bug, which probably won't be soon.

**Comment by Dook1** [comment]
I'll think about it.

**Comment by Dook1** [comment]
Option "Fix firefox bug1538119" аdded in 2.6.0
